### ISSUE TITLE
陽性患者の属性がスクロールできることがわかりづらい

### ISSUE THREAD

**Issue by rnsk** [CODE-for-GIFU/covid19#110]
## 改善詳細 / Improve details
* データテーブル内でスクロールできることがわかりづらい
* 見えているものがすべてだと勘違いしやすい

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-29 15 56 21](https://user-images.githubusercontent.com/512413/77843206-dee8e880-71d5-11ea-900d-f797136de0bd.png)

## 期待する見せ方・挙動 / Expected behavior
* 高さ指定を無くしページングを有効にする？

**Comment by rnsk** [comment]
ページングを実装するにあたって画像のとおり配置を変更したいのですがいかがでしょうか？

トップ画面上部
![top01](https://user-images.githubusercontent.com/512413/77866090-7bf66080-726c-11ea-87c1-c50f8d73a834.jpg)

トップ画面下部（ページング実装後イメージ）
![top02](https://user-images.githubusercontent.com/512413/77866103-8b75a980-726c-11ea-93be-927427e3e31c.jpg)

**Comment by iamakawa** [comment]
素晴らしいですね！養成患者の属性はそれでいきましょう。

ただし、他のビューについては悩みどころです。
具体的には、「検査実施数」の掲載をやめたらどうかと考えています。

岐阜県の掲載ですが、3/26時点で止まっています。
![image](https://user-images.githubusercontent.com/15156125/77866337-8c5b0b00-726d-11ea-9637-a65d1c85d5c6.png)
おそらく本日、3/30日分として更新されると予想すると、
また数値がとびとびになります。
・そのたびに注釈をつけると情報量そのものが多くなる。
　つまり、誤解のリスクが高まると考える。
・その状況で、この情報を掲載し続ける嬉しさ、とは・・と思っています。

そのため、表示ブロックとしては、以下が良いと考えますがいかがでしょうか？
・検査陽性者の状況　　・陽性患者数
・陽性患者の属性(2ブロックぶちぬき)

**Comment by rnsk** [comment]
なるほど。
推移が見れないのであればグラフにする意味もないですね。。。
ご提案いただいた表示方法にします！

**Comment by iamakawa** [comment]
ありがとうございます。ただし、オープンデータ提供などで、毎日情報を提供できる体制が整えば、表示方法は↑で良いと思います。それはまたデータが揃ったときに考えましょう。
