### ISSUE TITLE
「オープンデータへのリンク」見直し

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#119]
## 改善詳細 / Improve details
* 「オープンデータへのリンク」で県Webサイトにリンクしているが、実際は違うデータを参照している
* 「検査実施数」のオープンデータへの「リンク」は除外できないか
* 「陽性患者の属性」はテーブルの列ごとに個別のPDFにジャンプできないか

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/15156125/77973053-1c608980-732e-11ea-9c70-07979dd9909b.png)
![image](https://user-images.githubusercontent.com/15156125/77973076-2da99600-732e-11ea-8f0f-a7f1e74f4b08.png)

**Comment by rnsk** [comment]
オープンデータへのリンクはすべて削除でよいと思います。
岐阜県のサイトが1ページに集約されているので、そのページへのリンクは別の箇所で用意してはどうかと。
PDFへのリンクは端末によってはダウンロードになる場合があるのであまりやりたくないかな。

**Comment by iamakawa** [comment]
そうですね。オープンデータへのリンクで良いと思います。
データですが、岐阜県のサイトだけを見ているだけではなく、今は可児市のサイトも見ています。

「本サイトについて」のところで、
・本サイトで公開しているデータは県内の行政が公開したデータをもとに作成しています。
　詳細は各行政のWebサイトをご覧ください。という文言を足す、

というのはどうでしょう？
ゆくゆくは、「窓口情報一覧」ページを新設し、そこへのリンクを貼れればと考えています。

**Comment by rnsk** [comment]
承知しました。

**Comment by iamakawa** [comment]
対応します。
