### ISSUE TITLE
リンク文字色の変更

### ISSUE THREAD

**Issue by rnsk** [CODE-for-GIFU/covid19#13]
## 改善詳細 / Improve details
* 全体の色が水色のため、同系色（青色）のリンク文字が目立たないような気がする
* リンクの文字色を変更してはどうか

## スクリーンショット / Screenshot
![県内の最新感染動向___岐阜県_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/512413/76714186-0917c080-6769-11ea-9e30-3b498b40786d.jpg)

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
*

**Comment by tetsuji1122** [comment]
assets/variables.scssで$linkを「#228b22」緑色にしてみました。しかし、オープンデータへのリンクの部分の文字の色は変わりませんでした。
