### ISSUE TITLE
データを表示している部分が多言語化されない

### ISSUE THREAD

**Issue by tetsuji1122** [CODE-for-GIFU/covid19#135]
## 起こっている問題 / Occurred problem
* データを表示している部分が多言語化されない
* DataTable.vueの直し方がわからない

## スクリーンショット / Screenshot
![コメント 2020-04-04 114918](https://user-images.githubusercontent.com/10161444/78417156-6321ec80-766a-11ea-9ff5-84174599ffed.png)

**Comment by iamakawa** [comment]
東京都のデータ表示部ですが、翻訳タグ(this.$t)を配置してるっぽいですね。

https://github.com/tokyo-metropolitan-gov/covid19/blob/development/components/cards/ConfirmedCasesAttributesCard.vue

![スクリーンショット 2020-04-04 15 30 05](https://user-images.githubusercontent.com/15156125/78420349-303b2100-7689-11ea-90a5-b8c12395b4a5.png)

**Comment by rnsk** [comment]
https://github.com/CODE-for-GIFU/covid19/blob/development/pages/municipalities.vue#L55
先日追加した一覧表での処理です。
DataTable.vue は共通ファイルなので、データを渡す前に加工する必要があるかと思います。

**Comment by tetsuji1122** [comment]
表示のところで変換かけたいけど共通部品だと難しいのかあ

**Comment by iamakawa** [comment]
DataTableに渡す前の処理でいけそうです。
今日出てきた10代以下の記載ルールが悩みどころですね。

![スクリーンショット 2020-04-04 21 36 29](https://user-images.githubusercontent.com/15156125/78450837-6c3ba980-76bc-11ea-8f97-7ff6e3e8f72a.png)
