### ISSUE TITLE
データグラフの一部が多言語化されない

### ISSUE THREAD

**Issue by rnsk** [CODE-for-GIFU/covid19#139]
## 起こっている問題 / Occurred problem
* グラフ内上部の累計や実績値が多言語化されていない

## スクリーンショット / Screenshot
![県内の最新感染動向___岐阜県_新型コロナウイルス感染症対策サイト](https://user-images.githubusercontent.com/512413/78463581-56a89d00-7719-11ea-8673-3a8605ea2b16.jpg)

**Comment by rnsk** [comment]
対応します

**Comment by iamakawa** [comment]
ごめんなさい、見落としていました。
累計がこうし更新されていないので、こちらも対応してもらっていいですか?
![スクリーンショット 2020-04-05 10 06 49](https://user-images.githubusercontent.com/15156125/78464510-6f1eb480-7725-11ea-942b-bceb1c5ce533.png)

**Comment by rnsk** [comment]
累計の部分は翻訳を追加していただくと適用されます。
`{patientsDate}の累計` で翻訳ファイルに追加してみてください。

**Comment by iamakawa** [comment]
あ、そうか！失礼しました。

**Comment by iamakawa** [comment]
何度もOpen/Closeしてすみません。翻訳ファイルが追加された時点でCloseとします。

**Comment by iamakawa** [comment]
翻訳ファイルが追加されましたので、Closeします。
