### ISSUE TITLE
岐阜県自治体コロナ対策情報一覧の表示について

### ISSUE THREAD

**Issue by site-lab** [CODE-for-GIFU/covid19#143]
## 改善詳細 / Improve details
* 50音順と後から気づいたので、どこかに50音順とかの表記があるとわかりやすい

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
*Windows10/chrome

**Comment by rnsk** [comment]
対応します

**Comment by site-lab** [comment]
> 対応します

スクリーンショットで確認できました。ありがとうございます。本番は今みたらまだ反映されていなかったのですが、どこかで反映されるということでよいでしょうか？

**Comment by rnsk** [comment]
development にマージされた段階なので、開発版に反映されています。
https://dev-covid19-gifu.netlify.com/

参考までに開発のながれは次のとおりです。
1. ISSUEコメントにて対応することを表明する
2. 自身の環境で修正
3. development にプルリクエストを送信
4. development にマージ
5. 開発版サイトに反映 --- この段階でISSUEが閉じられることもある
6. 開発版で問題なければ master にプルリクエストを送信
7. 管理者がレビュー
8. master にマージ
9. 本番サイトに反映

**Comment by site-lab** [comment]
> development にマージされた段階なので、開発版に反映されています。
> https://dev-covid19-gifu.netlify.com/
> 
> 参考までに開発のながれは次のとおりです。
> 
> 1. ISSUEコメントにて対応することを表明する
> 2. 自身の環境で修正
> 3. development にプルリクエストを送信
> 4. development にマージ
> 5. 開発版サイトに反映 --- この段階でISSUEが閉じられることもある
> 6. 開発版で問題なければ master にプルリクエストを送信
> 7. 管理者がレビュー
> 8. master にマージ
> 9. 本番サイトに反映

ありがとうございます。流れ把握しました。失礼しました
