### ISSUE TITLE
岐阜県のオープンデータカタログサイトから値を取得できるようにする

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#145]
**現在調整中**

## 改善詳細 / Improve details
* 岐阜県オープンデータカタログサイトに、covid-19関連のオープンデータが掲載される予定である。
* 4/8段階では未公開だが、公開された段階で順次接続する。

## 技術課題
* オープンデータカタログサイトからの情報取得
* 本サイトへのデータの反映

## 参考資料
* Code for JAPAN covid-19 オープンデータ項目定義書
 https://www.code4japan.org/activity/stopcovid19

**Comment by tetsuji1122** [comment]
これはクローズでいい？

**Comment by iamakawa** [comment]
はい、クローズでOKです。クローズします。
