### ISSUE TITLE
岐阜県自治体コロナ対策情報一覧の翻訳追加

### ISSUE THREAD

**Issue by rnsk** [CODE-for-GIFU/covid19#147]
## 改善詳細 / Improve details
* #143 の修正で文言を追加したので翻訳も追加したい

- 50音順
- 自治体名またはふりがなで検索

## スクリーンショット / Screenshot
![スクリーンショット 2020-04-08 9 49 06](https://user-images.githubusercontent.com/512413/78732735-71c81680-797e-11ea-8eda-7ec729a1b430.png)

**Comment by tetsuji1122** [comment]
翻訳については対応します
