### ISSUE TITLE
最新のお知らせ（岐阜県公式HPより）

### ISSUE THREAD

**Issue by site-lab** [CODE-for-GIFU/covid19#151]
## 改善詳細 / Improve details
* 2020/04/06　新型コロナウイルス感染症について 
→リンク先がhttps://www.pref.gifu.lg.jp/kinkyu-juyo-joho/shingata_corona.html となっていて、どの情報をさしているのかわかりづらい。
※最新版が4月7日になっている（岐阜県公式サイト）

## 期待する見せ方・挙動 / Expected behavior
* 最新情報をクリックしたら個別ページへ行く（知事メッセージのように）

## 動作環境・ブラウザ / Environment
* Windows10/chrome

**Comment by rnsk** [comment]
こちらは県のお知らせから新型コロナウィルスに関するお知らせを確認して掲載しています。
現在は県のサイト側に個別のページが用意されていないので対応しておりません。
![スクリーンショット 2020-04-08 14 05 53](https://user-images.githubusercontent.com/512413/78746553-29baeb00-79a2-11ea-8ef2-f15df7e2dfaa.png)
