### ISSUE TITLE
陽性患者の状況で「入院調整中」に対応する

### ISSUE THREAD

**Issue by tetsuji1122** [CODE-for-GIFU/covid19#160]
## 改善詳細 / Improve details
* すぐに「入院」できるわけでは無さそうなので「入院調整中」の状態も増えてくると思います

宮城県のサイトでは対応したようです。
https://miyagi.stopcovid19.jp/

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
*

**Comment by tetsuji1122** [comment]
それとも岐阜県庁の画像が対応したら対応すればいいのかな？

**Comment by iamakawa** [comment]
宮城はこれですね。
個人的には、岐阜県が対応していなくても対応したいところです。
県から日毎の検査数データを受領できれば、
・黒色部分を無くして表示
・日毎の検査数グラフを表示
すれば良さそう

![image](https://user-images.githubusercontent.com/15156125/78949357-3d7f6200-7b06-11ea-8ab2-28f5afbc947e.png)
![image](https://user-images.githubusercontent.com/15156125/78949536-c8f8f300-7b06-11ea-8d7c-b377b8b0b465.png)

**Comment by rnsk** [comment]
データがあれば即対応したいですね。
検査実施件数は残しておきたいかな。

**Comment by iamakawa** [comment]
懸念点としては、
・県が参照しようとしているオープンデータ定義書に、「入院準備中」の定義が無い。
　https://www.code4japan.org/activity/stopcovid19#doc
　→どうデータ設定をする？かが課題になります。
・検査実施件数を残したままにして表示を横8ブロックにすると、横の表示項目が小さくなり、スマホだと読みにくくなるのでは
![image](https://user-images.githubusercontent.com/15156125/78949742-808e0500-7b07-11ea-9e8f-718472bd1323.png)

**Comment by iamakawa** [comment]
岐阜県としては入院中+入院調整中なので、合せたほうが良いかと思いますがいかがでしょうか。
![スクリーンショット 2020-04-11 6 56 36](https://user-images.githubusercontent.com/15156125/79025884-079fb380-7bc2-11ea-8ba7-c605d165a7bc.png)

**Comment by tetsuji1122** [comment]
いいと思います。それなら簡単に修正できそうです

**Comment by iamakawa** [comment]
<現状対応>
入院中も、入院対応中も、合同で計測する。

<オープンデータ接続後を見据えての対応>
オープンデータ定義書で確認できるのは、「退院済フラグ」「患者状態(死亡)」のみです。
・退院済フラグ　= 1 かつ
　・患者状態　= 死亡 　：死亡
　・患者状態　!= 死亡　：退院
・退院済フラグ　!= 1 の場合、
　・入院中・入院調整中でカウント
　・ただし、現時点で軽症・中等症と重症を区分けできるものがありませんね。
　　これは、問題点として報告します。

**Comment by iamakawa** [comment]
対応します。
