### ISSUE TITLE
TOPページ陽性患者の属性の一覧表示について

### ISSUE THREAD

**Issue by site-lab** [CODE-for-GIFU/covid19#169]
## 改善詳細 / Improve details
* ブラウザで表示方法が違う？
chrome/IE11：日付が最新（4/12）が一番上
firefox：日付が最古（2/26）が一番上

## 期待する見せ方・挙動 / Expected behavior
* firefoxでも日付が最新になるとありがたい

## 動作環境・ブラウザ / Environment
* chrome、firefox、IE11

**Comment by iamakawa** [comment]
ありがとうございます。当方のFirefox75.0 (64 ビット)でもそのようになることを確認しました。
![image](https://user-images.githubusercontent.com/15156125/79084500-15df0280-7d6f-11ea-8efd-6c71e9af2393.png)

**Comment by iamakawa** [comment]
対応します。

**Comment by iamakawa** [comment]
#181 で並び順を指定し、#171 のNo.で並び順指定しました。closeします。
