### ISSUE TITLE
相談窓口一覧のデータをJSONから読み込む

### ISSUE THREAD

**Issue by tetsuji1122** [CODE-for-GIFU/covid19#176]
## 改善詳細 / Improve details
* 更新頻度の高くないデータはJSONから静的に読み込みキャッシュ化したい

* アクセス数が増加したときの対応可能

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
*

**Comment by iamakawa** [comment]
これもクローズしてよかったでしたっけ?

**Comment by tetsuji1122** [comment]
クローズしましょう

**Comment by iamakawa** [comment]
了解です、クローズしますねー。
