### ISSUE TITLE
県内飲食店のテイクアウト情報紹介サイトを掲載する

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#178]
## 改善詳細 / Improve details
* 別団体、別地域で飲食店のテイクアウト情報を掲載するWebサイトが立ち上がっている。
 地域ごとに紹介するページを作る

http://takeout-gifu.com/
http://gifu-takeout.com/
https://uchi-g.com/
https://takeout.kamo-it.com/
https://www.lets-gifu.com/g/search/genrep-15/genre-77/

**Comment by rnsk** [comment]
情報過多になるような気がします。

**Comment by iamakawa** [comment]
掲載した自分が言うのもなんですが、すでに乱立しており制御が難しいですね。
別ページ独立で考えていましたが・・
一番↓のリンクのように、岐阜県版食べログみたいなページもありますね。

**Comment by iamakawa** [comment]
対応しないこととします。そのためクローズです。
