### ISSUE TITLE
岐阜県公認の説明をかんがえる

### ISSUE THREAD

**Issue by tetsuji1122** [CODE-for-GIFU/covid19#180]
## 改善詳細 / Improve details
* 当サイトaboutに公認時の文言をかんがえる

本家、東京都のサイトを参考にする
県庁の方に確認する

**Comment by iamakawa** [comment]
東京都は公式なので、同じ属性となる富山県を参考に考えてみましたがいかがでしょうか。
https://stopcovid19-toyama.netlify.app/about

===
当サイトは新型コロナウイルス感染症（COVID-19）に関する最新情報を提供するために、岐阜県が提供しているデータを元に CODE for GIFU が開設したものです。

2020/05/XXより岐阜県の公認サイトとなりました。運営は引き続き有志が行っています。

岐阜県による公式情報と客観的な数値をわかりやすく伝えることで、岐阜県にお住まいの方や、岐阜県内に拠点を持つ企業の方、岐阜県を訪れる方が、現状を把握して適切な対策を取れるようにすることを目的としています。 

※ 当サイトは複製・改変が許されたオープンソースライセンスの下で公開されている、東京都新型コロナウイルス感染症対策サイトの仕組みを利用しています。

**Comment by rnsk** [comment]
> 岐阜県が提供している
「提供している」は差し出す側の言葉ではないでしょうか。
岐阜県より提供されている、もしくは、岐阜県が公開している・の方が良いと思います。
直前に「最新情報を提供するため」とあるので後者かな。

**Comment by iamakawa** [comment]
ありがとうございます。「岐阜県が公開している」ですね。

**Comment by iamakawa** [comment]
予想より1日、更新が早かったので少し修正のため、issueをreopenします。
