### ISSUE TITLE
サマリーが岐阜県サイトと表現が異なる

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#213]
## 改善詳細 / Improve details
* 「後方施設入所中」を含んでいない
* 「患者属性」の退院済フラグについて、「療養解除を含む」

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/15156125/82270088-9ae0bb80-99ae-11ea-88e6-0b034f74cf38.png)
![image](https://user-images.githubusercontent.com/15156125/82270093-9d431580-99ae-11ea-9cf5-bb75facefcdf.png)

**Comment by iamakawa** [comment]
![image](https://user-images.githubusercontent.com/15156125/82271352-7e468280-99b2-11ea-9e38-5e2eb82fed4c.png)
なんとなく表示がごちゃっとする気がするのでやめていましたが、案外そうでもない・・？
問題なさそうならこれでプルリクだそうと思います。

**Comment by tetsuji1122** [comment]
よくやるのは注釈をつける方法ですかね？

入院中※1

欄外に
※1 入院中、入院調整中、後方施設入所中を含む

**Comment by rnsk** [comment]
英語などの表記だとさらに長くなると思うので、石井さんの案が良いかなと思います。

**Comment by iamakawa** [comment]
ありがとうございます。注釈案でいきたいと思います。
