### ISSUE TITLE
県主催イベント・県有文化施設等の対応状況　リンク切れ

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#218]
https://www.pref.gifu.lg.jp/shingata_corona_enki.html
がリンク切れしている。

現在は、
https://www.pref.gifu.lg.jp/kinkyu-juyo-joho/shingata_corona_event_shisetsu.html
が相当するか?

**Comment by rnsk** [comment]
そうですね。
PDFになってしまいますが。。。

**Comment by iamakawa** [comment]
PDF、日付ごとのリンクとなっているので、ファイル名が一致しない恐れがあり、直リンクは危険ですね。
https://fukuno.jig.jp/2855
ほんとうは↑のように、施設ごとの状況がわかると一番嬉しいですよね。

**Comment by iamakawa** [comment]
暫定ですが、上記のリンクを貼ることで対応します。
