### ISSUE TITLE
アイコンのフォントをロゴに合わせる

### ISSUE THREAD

**Issue by rnsk** [CODE-for-GIFU/covid19#22]
## 改善詳細 / Improve details
* アイコンに使用しているフォントをロゴと同じものにする
* 装飾済みのフォント

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-17 13 06 53](https://user-images.githubusercontent.com/512413/76821050-355a3c80-6850-11ea-85b8-6ed0a87ca20a.png)

**Comment by tetsuji1122** [comment]
3/26 竹澤さんに以下のアイコンを作ってもらうようお願いした
static/icon.png

**Comment by rnsk** [comment]
対応します。
static/apple-touch-icon-precomposed.png
static/icon.png
