### ISSUE TITLE
Webサイトの改善要望を受け付ける機能を追加する

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#223]
## 改善詳細 / Improve details
* メールまたはフォームを想定
* 要望があった場合の全体のフローも併せて検討する。

**Comment by iamakawa** [comment]
Googleフォームの案
https://forms.gle/VBeVXFY8EQD6uJ6e7

**Comment by tetsuji1122** [comment]
名前は不要かも
メールアドレスについては「連絡用」としてください。目的をはっきり書いておくと良い。あと、必須のほうがいい。また注意書きとして以下を記述しておきましょう。
「※お問い合わせ内容の確認以外にメールアドレスを利用することはありません」

フォームの色合いいいですね。

**Comment by iamakawa** [comment]
ありがとうございます。名前は削除しました。
メールアドレスの注意書き、目的も記載しました。

メールアドレス、必須にしておいた方が良いですかね？スプレッドシートで回答を公表するのであれば、質問の意図が不明のため対応しない」みたいなことを回答しちゃっても良い気がしました。

**Comment by tetsuji1122** [comment]
お問い合わせ内容って公開するんでしたっけ？その辺りが、読み取れてなかったです。
ただ、こちらからの連絡は取れるようにしておいたほうが、トラブル時に対応できるかなと。

**Comment by iamakawa** [comment]
そうですね、メールアドレスは必須にしておきます。対応状況は全員に対しては公表しなくてもいいかもしれませんね。

**Comment by iamakawa** [comment]
・「当サイトについて」の一番下に「お問い合わせ」を付けることで対応します。
