### ISSUE TITLE
岐阜県サーバ更新に伴うリダイレクト先URLの点検

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#234]
## 改善詳細 / Improve details
* 岐阜県サーバが更新され、記事のURLが更新された。現在はリダイレクトされるが、今後更新されなくなることを踏まえ、リダイレクト先のURLに更新する。

**Comment by rnsk** [comment]
次のページ内にあるリンクが古いままでリンク切れも有り

・事業者の皆様へ
・宿泊事業者の皆様へ

情報の正確性と見やすさから、県のサイトへ誘導するよう変更してこちらのページは削除してはどうか
