### ISSUE TITLE
サマリー情報の更新(県内/県外の対応、東京都表示への追従)

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#235]
## 改善詳細 / Improve details
感染者の総計が県外検査後、県内で受け入れた患者も含むようになったため、サマリーの表現内容を検討する。
①こちらは合計だけにして注釈に「他自治体～」を入れるパターン
②県内、県外を明確に分けるパターン
のどちらか。②のほうが正確だが、今より1コ要素が横に増えるので、更に狭くなる欠点がある。
![image](https://user-images.githubusercontent.com/15156125/105781102-3e11b800-5fb5-11eb-8da3-f25c1c3643af.png)
![image (1)](https://user-images.githubusercontent.com/15156125/105781109-423dd580-5fb5-11eb-938a-afeb5f1eaff6.png)

そこで、東京都のサイトがより見やすいと考えられるため、こちらに表示を合わせる
- 多言語表示で表示が崩れにくい
- サマリーの表示項目増減に対応しやすい

<img width="565" alt="スクリーンショット 2020-10-10 21 30 24" src="https://user-images.githubusercontent.com/15156125/95655125-17cc2780-0b40-11eb-9c0e-0c3dfea68b83.png">

**Comment by iamakawa** [comment]
こちら、東京都のデザインにしたうえで、1,2の両方を実装、どちらが良いか検討してみます。

**Comment by rnsk** [comment]
現状のまま検査実施件数を除いて東京のデザインにしてみました。
こんな感じになります。
![スクリーンショット 2021-01-27 10 10 36](https://user-images.githubusercontent.com/512413/105927742-f4de6880-6087-11eb-94d7-614c870790c7.png)

**Comment by rnsk** [comment]
検査実施件数も入れたバージョン。
つまり現状からデザインだけが変わったものです。
見やすい。
https://rnsk-dev-covid19.netlify.app/

![スクリーンショット 2021-01-27 17 18 08](https://user-images.githubusercontent.com/512413/105964146-245f9600-60c5-11eb-9b58-ee87579f163b.png)

**Comment by iamakawa** [comment]
もろもろありがとうございます！slackでの議論のとおりですが、2枚目のバージョン(現行そのまま)だと、感染者数と検査数が食い違うことになるため、避けたいです。1枚目の方がシンプルでしっくりきますね。

**Comment by rnsk** [comment]
間違えてプルリクしてた。。。
1枚目でプルリクしなおします。

**Comment by iamakawa** [comment]
https://github.com/CODE-for-GIFU/covid19/issues/283 も含めて追従済、クローズとする。
