### ISSUE TITLE
県HP上での表現と合わせる

### ISSUE THREAD

**Issue by rnsk** [CODE-for-GIFU/covid19#240]
## 改善詳細 / Improve details
* 県HP上での表現を一部変更しましたので、合わせていただけば幸いです。
1. 「かかりつけ医等の医療機関で対応できない場合」⇒「かかりつけ医を持たない方」
2. 「どこに相談したら良いか分からない方」⇒「相談先に迷う方」

## 期待する見せ方・挙動 / Expected behavior
* xxxx(できるだけ簡潔に/as concise as possible)

## 動作環境・ブラウザ / Environment
*

**Comment by rnsk** [comment]
対応します

**Comment by rnsk** [comment]
↓これも

「帰国者・接触者相談センター」を「受診・相談センター」に名称変更しました。
サイトの「帰国者・接触者相談センター相談件数」を「受診・相談センター相談件数」にしてください。

**Comment by iamakawa** [comment]
![image](https://user-images.githubusercontent.com/15156125/96428805-29e25000-123b-11eb-9ac5-92a28b45846d.png)
すみません、上の文言ばかり見ていて、下の文言をすっかり見落としていました・・。
reopenします。
