### ISSUE TITLE
要請患者の属性一覧の表示変更(県外対応、退院済フラグの変更)

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#259]
## 改善詳細 / Improve details
- 県外表示に対応#235 にも追従
- 退院済フラグを追加するかどうか検討
- 掲載する項目の候補は「日付、居住地、年代、性別、検査地（県内 or 県外）、退院済フラグ」

## 期待する見せ方・挙動 / Expected behavior
- スマホ表示にも耐えうるかどうか検討が必要
![image (2)](https://user-images.githubusercontent.com/15156125/105781356-cf812a00-5fb5-11eb-8c21-6f7252f3e6dd.png)

**Comment by rnsk** [comment]
対応します。
