### ISSUE TITLE
サイドバーの下部の背景が無くなる

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#262]
## 起こっている問題 / Occurred problem
* 写真のとおり。背景が途切れてメインページと同色になる。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/15156125/106565844-ca524b00-6572-11eb-84ca-0d36d88ed59b.png)

**Comment by rnsk** [comment]
対応します。
