### ISSUE TITLE
後方支援病棟導入における、サイト記載の変更

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#267]
## 改善詳細 / Improve details
* 岐阜県が「後方支援病棟」を導入した。 https://www.chunichi.co.jp/article/196951
* 「後方支援病床」とは：新型コロナウイルスの治療を終えた後に退院までリハビリが必要な高齢患者を受け入れる施設
* それにあたり、下記、「後方施設」の記載が曖昧になるため、下記のように記載を修正する。

・修正前
　「入院中」には、入院調整中、後方施設入所中を含む。
・修正後
　「入院中」には、入院調整中、宿泊療養施設入所中を含む。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/15156125/107132667-50301680-6924-11eb-922c-87cefa1a51de.png)

**Comment by rnsk** [comment]
対応します。
