### ISSUE TITLE
グラフに表示するデータの期間を選択出来るようにする

### ISSUE THREAD

**Issue by Chaha1n** [CODE-for-GIFU/covid19#277]
## 改善詳細 / Improve details
* 現在、感染者数のグラフは1年半程のデータが1つに表示されており見づらいため、表示期間を選択できるようにすると良いのではないかと感じました。

## 期待する見せ方・挙動 / Expected behavior
* グラフ下部に期間を選択するバーやドロップダウンリストのようなUIを追加する。  例) [愛知県版感染症対策サイト](https://stopcovid19.code4.nagoya/)

**Comment by iamakawa** [comment]
こんばんは、CODE for GIFUの天川です。ご提案いただきありがとうございます。
期間選択バーについては[北海道](https://stopcovid19.hokkaido.dev/)が初めて導入した際に、全体が見えにくくなることを危惧して入れない選択をしましたが、運営の期間が長期化し、ユーザーが選択できるようにしないと不便かもしれませんね。
![image](https://user-images.githubusercontent.com/15156125/127331924-559d0569-51db-442e-9acd-4887f650b1ab.png)

**Comment by Chaha1n** [comment]
>北海道が初めて導入した際に、全体が見えにくくなることを危惧して入れない選択をしました

そういう背景もあったのですね。

ぜひ検討頂けますと幸いです。

**Comment by iamakawa** [comment]
こちらありがとうございました!　データ区間を入力できるようなプログラム変更を入れた版を開発しておりますので、遅くなりましたが本issueはクローズしております。

**Comment by Chaha1n** [comment]
コミットやレビューに参加できず申し訳ないです🙏
素早い実装ありがとうございます！
