### ISSUE TITLE
検査実施人数と検査実施数の単位がズレている（人、件）

### ISSUE THREAD

**Issue by mikkame** [CODE-for-GIFU/covid19#33]
## 起こっている問題 / Occurred problem
* xxxx(できるだけ簡潔に/as concise as possible)

## スクリーンショット / Screenshot

<img width="383" alt="スクリーンショット 2020-03-18 20 26 45" src="https://user-images.githubusercontent.com/13947046/76956379-49d52c80-6957-11ea-94e9-c65de21ebafd.png">
<img width="381" alt="スクリーンショット 2020-03-18 20 26 38" src="https://user-images.githubusercontent.com/13947046/76956382-4b065980-6957-11ea-9090-f637723bba5e.png">

## 期待する見せ方・挙動 / Expected behavior
* 検査人数は検査した人の人数
* 検査件数は1人にたいして、何回も実施する可能性がある→検体数

## 起こっている問題の再現手段 / Steps to reproduce
1. まず一次ソースを確認したい

## 動作環境・ブラウザ / Environment
*

**Comment by iamakawa** [comment]
検査実施人数→検査実施数に変更する
(入力ソースは件数であるため(

**Comment by iamakawa** [comment]
対応します。
