### ISSUE TITLE
相談窓口一覧をスプレッドシートでデータ化する

### ISSUE THREAD

**Issue by tetsuji1122** [CODE-for-GIFU/covid19#35]
岐阜県がPDF資料で出している相談窓口一覧をデータ化したい

https://www.pref.gifu.lg.jp/kinkyu-juyo-joho/shingata_corona.data/5_0316_b4.pdf

**Comment by iamakawa** [comment]
#16 に関連

**Comment by tetsuji1122** [comment]
こちらで一覧化と住所・緯度経度づけしました。
https://docs.google.com/spreadsheets/d/10b0NTVctq3jjSvaA6-Vc-dQJYt5FFEP292MLzkCdazs/edit?usp=sharing
