### ISSUE TITLE
多言語化メニューの追加

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#38]
## 改善詳細 / Improve details
* #7 より分岐。東京都のように、複数の言語化に対応し、ボタンで切り替えできるようにしたい
* 多言語化メニューの追加

## 📷スクリーンショット
![WS000004](https://user-images.githubusercontent.com/15156125/77017553-21cce400-69be-11ea-8728-467b920deefc.JPG)

**Comment by rnsk** [comment]
対応します
