### ISSUE TITLE
多言語化メニューでGoogleスプレッドシートから読み込みできるようにしたい

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#39]
## 改善詳細 / Improve details
* #7 より分岐。多言語化対応において、Googleスプレッドシートから値を読みたい

## 参考URL
言語参考。岐阜県版のシートも順次作りたい
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit?usp=sharing

できれば Google スプレッドシートのデータをそのまま使いたい
参考：[Nuxt.jsからGoogleスプレッドシートのデータを読み書きする](https://www.virment.com/read-write-google-spreadsheet-from-nuxtjs/)

## 補足
* 他の事例だと、Googleスプレッドシートの管理は行っていないところもあり。
　要技術調査

**Comment by tetsuji1122** [comment]
更新頻度はそれほど高くないのでJSONのままでも良い気がします。

**Comment by rnsk** [comment]
私も管理はスプレッドシートで、サイトに使用するのはJSONのままで良いと思います。
対象がサイト全体におよぶのでJSONのままのほうが表示速度は早いです。
スプレッドシート→JSON化を半自動化しているところはありますが、現時点でそこまで手をかける必要もない気がします。

**Comment by tetsuji1122** [comment]
JSONファイルの運用のままとするため、クローズしてもいいですか？

**Comment by iamakawa** [comment]
良いと思います。closeしました。
