### ISSUE TITLE
サーバ変更・ドメイン名の変更

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#41]
## 改善詳細 / Improve details
* CODE for JAPANにstopcovid19.jp のサブドメインを提供いただける動きあり。現在申請中。
  申請が通れば、ドメイン名を変更する。
* さくらインターネットが新型コロナウイルス対応のためのサーバーを提供いただける動きあり。現在申請中。

**Comment by tetsuji1122** [comment]
さくらへの移行時にドメイン名も移行する。
まずはさくらインターネットの担当者にどのように環境を提供してもらえるのか確認をします

**Comment by tetsuji1122** [comment]
現時点でさくらインターネットをつかうメリットがないため、サーバー移行はしない。必要になったタイミングでドメインも含めて検討するためクローズ
