### ISSUE TITLE
Githubアイコンを掲載、Githubページをリンクする

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#6]
## 改善詳細 / Improve details
* 東京都と同じようにGithubへのリンクを掲載したい

## スクリーンショット / Screenshot
<img width="328" alt="スクリーンショット 2020-03-14 10 18 05" src="https://user-images.githubusercontent.com/15156125/76672003-3172b400-65dd-11ea-9a70-73f8b06e7316.png">

**Comment by rnsk** [comment]
やります。
