### ISSUE TITLE
8人目まで追加

### ISSUE THREAD

**Issue by rnsk** [CODE-for-GIFU/covid19#67]
## 改善詳細 / Improve details
* 感染者が増えたのでデータを更新する

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-24 8 26 50](https://user-images.githubusercontent.com/512413/77372592-4d2e4500-6da9-11ea-93bd-3e913a817f88.png)

https://www.pref.gifu.lg.jp/kinkyu-juyo-joho/shingata_corona.html

**Comment by iamakawa** [comment]
対応します。
