### ISSUE TITLE
json直書きの情報をスプレッドシート読み込みに変更する

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#68]
## 改善詳細 / Improve details
* 現状、患者数、検査数、患者表、相談件数に関して、json直書きになっている箇所を
　スプレッドシートに書くだけで更新できるようにしたい

**Comment by iamakawa** [comment]
データシートの試作品は以下の通り
https://docs.google.com/spreadsheets/d/15CHGPTLs5aqHXq38S1RbrcTtaaOWDDosfLqvey7nh8k/edit?usp=sharing

**Comment by rnsk** [comment]
グラフごとにデータを分けた方が管理しやすいと思います。
スプレッドシートならシートを分けるだけでも良いです。

**Comment by iamakawa** [comment]
ありがとうございました。出力したいjsonの単位で1シートに分けています。
出力しているjsonは下記です。
https://script.google.com/macros/s/AKfycbxmIsCGDHHH0OIRSli-P_uuXKt9B6Y7GFUSKf5PVSIylzw93sk/exec

現在、開発を進めておりましたが、技術的な問題で進捗悪い状態です。
他の方でも解決できるようであれば、着手していただけるとありがたいです。
