### ISSUE TITLE
多言語対応

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#7]
## 改善詳細 / Improve details
*東京都「i18n」を対応させたい
*独自の文書もあるため追従させたい

**Comment by rnsk** [comment]
参考リンク
https://github.com/tokyo-metropolitan-gov/covid19/pull/854

**Comment by iamakawa** [comment]
言語参考。岐阜県版のシートも順次作りたい
https://docs.google.com/spreadsheets/d/1aksSfWIXE_L3rFYFjHz9xtVhh0n7ealMQ0eEz8GGPlw/edit?usp=sharing

**Comment by rnsk** [comment]
できれば Google スプレッドシートのデータをそのまま使いたい
参考：[Nuxt.jsからGoogleスプレッドシートのデータを読み書きする](https://www.virment.com/read-write-google-spreadsheet-from-nuxtjs/)

**Comment by iamakawa** [comment]
issueを細分化したためクローズ
