### ISSUE TITLE
「検査陽性者の実施件数」≠「検査実施数の合計」

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#82]
## 起こっている問題 / Occurred problem
* 「検査陽性者の状況」内の検査件数と検査実施数の数が合わない

## 原因 / Cause
* 岐阜県は最新時点での累積件数のみ公開している
* Webサイトでは日毎の件数の累積で累積件数を計算する仕組み

## スクリーンショット / Screenshot
![WS000014](https://user-images.githubusercontent.com/15156125/77597324-d5dfe900-6f41-11ea-9157-feddb4fde86a.JPG)

**Comment by rnsk** [comment]
毎日の累積件数を記入して前日との差分を日毎の実施数とする？

**Comment by iamakawa** [comment]
本日以降はそれでなんとかなりますが、3/11-3/23が計算できないのが直近の問題ですね。

**Comment by rnsk** [comment]
ウソはダメですね。
現状で追加するのであれば、最終日（3/23）にまとめて追加して注釈をつけたほうが良いと思います。
詳細情報いただけるとそれが一番良いのですが。

**Comment by iamakawa** [comment]
そうですね、一時的にそのように対応しましょう。
「3/23の追加件数は3/12-3/23の累積値である」と記載ですね。
今後も毎日更新されると良いのですが・・
