### ISSUE TITLE
クルーズ船受け入れの情報公開

### ISSUE THREAD

**Issue by iamakawa** [CODE-for-GIFU/covid19#83]
## 改善詳細 / Improve details
* 岐阜県Webサイトにて、クルーズ船受け入れの情報が公開されたので、追従したい。

## スクリーンショット / Screenshot
![WS000010](https://user-images.githubusercontent.com/15156125/77597416-25261980-6f42-11ea-8f8f-c19400ad7288.JPG)

**Comment by rnsk** [comment]
クルーズ船の情報は、岐阜県に住む・働く一般の方にとってどの程度必要な情報になりますでしょうか？
それほど必要なものでなければ、トップページではなく別ページに用意する、または、リンクを貼るといった方法で対応したいです。
スマートフォンでの閲覧も多いと思うので、トップページは必要な情報を簡潔にまとめたいと思っています。

**Comment by iamakawa** [comment]
当初、岐阜県が新たな情報として提供いただけていたので追従しようと考えましたが、
改めて考えると、混乱を与えるので不要ですね。リンクで飛ばすのなら、もう岐阜県のこのサイトで良いと思います。 クローズしますね。
